config/routes.rb
Justindao::Application.routes.draw do
  root to: "home#home"

  get '/main_projects', to: "main_projects#index", :as => "main_projects"
  get '/other_projects', to: "other_projects#index", :as => "other_projects"
  get '/contact', to: "home#contact", :as => "contact"

  get '/main_projects/theCourseForum', to: "main_projects#thecourseforum", as: "thecourseforum"
  
  get '/other_projects/Nuduro', to: "other_projects#nuduro", as: "nuduro"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
end

app/controllers/main_projects_controller.rb
class MainProjectsController < ApplicationController
  
end

app/controllers/other_projects_controller.rb
class OtherProjectsController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/contact.html.haml
.row
  .col-xs-12
    Email:
.row
  .col-xs-12
    Phone:
.row
  .col-xs-12
    LinkedIn:

app/views/home/home.html.haml
.wrapper
  .slider-wrapper.theme-default
    .ribbon
    #main_slider.ramblingSlider
      %img{:alt => "theCourseForum", :src => image_path("tCF_logo.png"), :title => "#theCourseForum-caption"}
      %img{:alt => "Nuduro", :src => image_path("nuduro_logo.png"), :title => "#nuduro-caption"}
    .rambling-html-caption#theCourseForum-caption
      = link_to "theCourseForum", thecourseforum_path
    .rambling-html-caption#nuduro-caption
      = link_to "Nuduro", nuduro_path
      
    

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.header-nav{role: "navigation"}
  .container
    %a.navbar-brand{href: root_path}
      Justin Dao
    %ul.nav.nav-pills.navbar-nav
      %li{:class => controller.controller_name == 'main_projects' ? "active" : nil}
        %a{:href => main_projects_path} Main Projects

      %li{:class => controller.controller_name == 'other_projects' ? "active" : nil}
        %a{:href => other_projects_path} Other Projects

      %li{:class => current_page?(contact_path) ? "active" : nil}
        %a{:href => contact_path} Contact

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Justin Dao
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      = yield

app/views/main_projects/_main_projects_sidebar.html.haml
%aside
  %ul.nav.nav-pills.nav-stacked
    %li{:class => current_page?(main_projects_path) ? "active" : nil}
      %a{href: main_projects_path} Main Projects

    %li{:class => current_page?(thecourseforum_path) ? "active" : nil}
      %a{href: thecourseforum_path} theCourseForum

app/views/main_projects/index.html.haml
.row
  .col-xs-3
    .row
      = render "main_projects_sidebar"

app/views/main_projects/thecourseforum.html.haml
.row
  .col-xs-3
    .row
      = render "main_projects_sidebar"
  .col-xs-8
    .row
      .image
        = image_tag "tCF_logo.png", :style => "max-width: 100%;"
      %p.goal
        %h3 Goal
        %p
          theCourseForum is a place where UVa students can share their facts and opinions about the classes and professors they have had at the University of Virginia. The site aims to make the task of choosing classes as easy as possible by providing distributions of past grades for the classes along with reviews of the classes by fellow students. 
        %p
          theCourseForum also works towards bringing vital web development skills to UVa students. Other than a single upper-level computer science course, UVa does not offer any course on web development. We hope to be able to bring these skills to a wider range of students, with theCourseForum as a basis for development.
      %p.about
        %h3 About
        %p
          I have been working on this project since Fall of 2012, and I am currently the lead developer for this project out of a team of six UVa students. This project was started by creators Jeff Bordogna and Alan Webb in 2005, and after a long era of the site being unmaintained, they began looking for a small group of UVa students to take up the future of the site. 

          We use the Ruby on Rails framework for our back end due to its versitility, growing community, and its low level of difficulty to teach to new developers interested in creating web applications.
        %h3 Links
        %p.website
          = precede "Website: " do
            = link_to "thecourseforum.com", "http://www.thecourseforum.com", :target => '_blank'
        %p.github
          = precede "Github: " do
            = link_to "github.com/thecourseforum/theCourseForum", "http://www.github.com/thecourseforum/theCourseForum", :target => '_blank'
        %p.facebook
          = precede "Facebook: " do
            = link_to "facebook.com/theCourseForum", "http://www.facebook.com/theCourseForum", :target => '_blank'
        %p.twitter
          = precede "Twitter: " do
            = link_to "twitter.com/theCourseForum", "http://www.twitter.com/theCourseForum", :target => '_blank'

app/views/other_projects/_other_projects_sidebar.html.haml
%aside
  %ul.nav.nav-pills.nav-stacked
    %li{:class => current_page?(other_projects_path) ? "active" : nil}
      %a{href: other_projects_path} Other Projects

    %li{:class => current_page?(nuduro_path) ? "active" : nil}
      %a{href: nuduro_path} Nuduro

app/views/other_projects/index.html.haml
.row
  .col-xs-3
    .row
      = render "other_projects_sidebar"

app/views/other_projects/nuduro.html.haml
.row
  .col-xs-3
    .row
      = render "other_projects_sidebar"